defaults: &defaults
  serviceName: "image-service" # Will be shared in most reasources naming convention
  region: "" # Region where your service will be deployed
  environment: &defaults.environment
    DEFAULT_QUALITY: 70
    SLS_IGNORE: favicon.ico
    SLS_VALID_PATH_REGEX: ".*"
    DEFAULT_CACHE_CONTROL: "max-age=2592000"

stages:
  dev:
    <<: *defaults
    bucketPolicy: ${file("./example-s3-bucket-policy.json")} # Path to bucket policy example
    corsOrigin: "https://domain.com" # CORS Origin for POST and DELETE methods
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: "domain.com" # ? Must be the same as below
      CUSTOM_DOMAIN: "domain.com" # ? Must be the same as above
      SECURITY_KEY: "" # A string to be used to unhash securty requests, disabled if leaved empty
      ACM_CERTIFICATE_ARN: ""
  staging:
    <<: *defaults
    bucketPolicy: ${file("./example-s3-bucket-policy.json")} # Path to bucket policy example
    corsOrigin: "https://domain.com" # CORS Origin for POST and DELETE methods
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: "domain.com" # ? Must be the same as below
      CUSTOM_DOMAIN: "domain.com" # ? Must be the same as above
      SECURITY_KEY: "" # A string to be used to unhash securty requests, disabled if leaved empty
      ACM_CERTIFICATE_ARN: ""
  prod:
    <<: *defaults
    bucketPolicy: ${file("./example-s3-bucket-policy.json")} # Path to bucket policy example
    corsOrigin: "https://domain.com" # CORS Origin for POST and DELETE methods
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: "domain.com" # ? Must be the same as below
      CUSTOM_DOMAIN: "domain.com" # ? Must be the same as above
      SECURITY_KEY: "" # A string to be used to unhash securty requests, disabled if leaved empty
      ACM_CERTIFICATE_ARN: ""
